CREATE TABLE IF NOT EXISTS `cic_data` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `cic_id` CHAR(40) NOT NULL check(cic_id REGEXP 'CIC-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    `time` TIMESTAMP NOT NULL,
    `hp1_energy_consumed` DECIMAL(14,6),
    `hp2_energy_consumed` DECIMAL(14,6),
    `hp1_heat_generated` DECIMAL(14,6),
    `hp2_heat_generated` DECIMAL(14,6),
    `boiler_heat_generated` DECIMAL(14,6),
    `hp1ActiveFrac` DECIMAL(3,2),
    `hp2ActiveFrac` DECIMAL(3,2),
    `boilerActiveFrac` DECIMAL(3,2),
    `lteFrac` DECIMAL(3,2) NOT NULL,
    `hp1_data_availability` TINYINT(1) NOT NULL,
    `hp1_defrost_frac` DECIMAL(3,2),
    `OLD_hp1_electrical_energy_counter` DECIMAL(14,6) NOT NULL,
    `OLD_hp2_electrical_energy_counter` DECIMAL(14,6),
    `OLD_hp1_thermal_energy_counter` DECIMAL(14,6) NOT NULL,
    `OLD_hp2_thermal_energy_counter` DECIMAL(14,6),
    `OLD_cv_energy_counter` DECIMAL(14,6) NOT NULL,
    PRIMARY KEY (`id`)
);